In [3]:
import numpy as np
a=np.array([1,2,3])
a

array([1, 2, 3])

In [6]:
a.size

3

In [7]:
np.info

<function numpy.info(object=None, maxwidth=76, output=None, toplevel='numpy')>

In [8]:
a=np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [9]:
a[4]=1

In [10]:
a

array([0., 0., 0., 0., 1.])

In [11]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [12]:
a[::-1]

array([1., 0., 0., 0., 0.])

In [16]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [17]:
np.nonzero

<function nonzero at 0x0000021D787FC4F0>

In [18]:
a=np.array([1,2,0,0])
a.nonzero

<function ndarray.nonzero>

In [20]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
import random
np.random.random((3,3,3))

array([[[0.70689211, 0.79773017, 0.56519507],
        [0.15092315, 0.93174083, 0.73947532],
        [0.61284949, 0.92767474, 0.78103061]],

       [[0.88676417, 0.65468519, 0.74394649],
        [0.0576709 , 0.27671989, 0.41900844],
        [0.35251297, 0.7862951 , 0.07448176]],

       [[0.18403582, 0.59531045, 0.16682508],
        [0.26006002, 0.84422379, 0.2043835 ],
        [0.6980799 , 0.64251208, 0.72221832]]])

In [33]:
a=np.random.random((10,10))
a.min()

np.float64(0.023180630266545044)

In [35]:
a=np.ones((5,5))
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
a=np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
a=np.pad(a,pad_width=1,constant_values=0)
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [40]:
np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [41]:
a=(())

array([5, 5])

In [44]:
a=np.zeros((8,8))
a[1::2,::2]=1
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [45]:
a[::2,1::2]=0
a

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [6]:
import numpy as np
np.tile([1,2],(3,3))

array([[1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2],
       [1, 2, 1, 2, 1, 2]])

In [4]:
np.tile([[0,1],[1,0]],(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
import random
z=np.random.random((5,5))
z=(z-z.min()/z.max()-z.min())
z

array([[ 0.32851065,  0.07871304,  0.72912797,  0.70614218,  0.88062573],
       [ 0.7548613 , -0.04760098,  0.06583888,  0.12936551,  0.71120539],
       [ 0.58607065,  0.01438868,  0.71689043,  0.19787836,  0.3237225 ],
       [ 0.30358775,  0.84717689,  0.06254284,  0.65643739,  0.2124188 ],
       [ 0.26194535,  0.31193952,  0.68130968,  0.22465225,  0.6168644 ]])

In [10]:
a=np.ones((5,3))
b=np.ones((3,2))

In [12]:
a.dot(b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [15]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[(a>3)&(a<8)]*=-1

In [16]:
a

array([ 1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [25]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


In [26]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

C:\Users\Shriya\AppData\Local\Temp\ipykernel_12516\548293649.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
C:\Users\Shriya\AppData\Local\Temp\ipykernel_12516\548293649.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
C:\Users\Shriya\AppData\Local\Temp\ipykernel_12516\548293649.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [28]:
a=np.array([1,2])
b=np.array([1,3])
np.intersect1d(a,b)

array([1])